### ISSUE TITLE
BUILD FAILED on IOS

### ISSUE THREAD

**Issue by taatiq882** [a7med-mahmoud/react-native-ml-kit#10]
using on M1 Mac

Failed to build iOS project. We ran "xcodebuild" command but it exited with error code 65. To debug build logs further, consider building your app with Xcode.app, by opening mustaqbill.xcworkspace.
Command line invocation:
    /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -workspace mustaqbill.xcworkspace -configuration Debug -scheme mustaqbill -destination id=12D92B4A-96CD-4871-96FD-9C0A5B7FD54C

User defaults from command line:
    IDEPackageSupportUseBuiltinSCM = YES

note: Using new build system
note: Planning
Analyze workspace

Create build description
Build description signature: f4aa7eb76e1c41b541f9b546ae266813
Build description path: /Users/talhaatiq/Library/Developer/Xcode/DerivedData/mustaqbill-fhemmipxsgoadjbxflibshapgaaz/Build/Intermediates.noindex/XCBuildData/f4aa7eb76e1c41b541f9b546ae266813-desc.xcbuild

note: Build preparation complete
note: Building targets in dependency order
/Users/talhaatiq/Documents/GitHub/P103-Mstqbl-App/ios/mustaqbill.xcodeproj: error: The linked library 'libPods-mustaqbill.a' is missing one or more architectures required by this target: x86_64. (in target 'mustaqbill' from project 'mustaqbill')

2022-06-29 18:09:26.542 xcodebuild[12083:734655] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionSentinelHostApplications for extension Xcode.DebuggerFoundation.AppExtensionHosts.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
2022-06-29 18:09:26.542 xcodebuild[12083:734655] Requested but did not find extension point with identifier Xcode.IDEKit.ExtensionPointIdentifierToBundleIdentifier for extension Xcode.DebuggerFoundation.AppExtensionToBundleIdentifierMap.watchOS of plug-in com.apple.dt.IDEWatchSupportCore
** BUILD FAILED **

**Comment by a7med-mahmoud** [comment]
Hey @taatiq882, thanks for waiting!
I wonder what React Native ML Kit packages and versions you have?
Also, it would be helpful to provide the `npx react-native info` output so I can get more context.

**Comment by a7med-mahmoud** [comment]
Hey there! I tried creating a new app and installing all RN ML Kit packages and running it on my M1 Mac but it seems like GoogleMLKit for iOS doesn't yet support Apple Silicon, so we will have to wait until Google supports it.
You can follow [the status of Apple Silicon support for GoogleMLKit iOS here](https://issuetracker.google.com/issues/178965151?pli=1).

**Comment by efstathiosntonas** [comment]
It's been almost a year and no Apple Silicon support yet :/

**Comment by a7medev** [comment]
@efstathiosntonas I'm running it on an M1 machine, did you try upgrading to the latest versions of RN ML Kit?

**Comment by efstathiosntonas** [comment]
@a7medev I have to install rosetta for it to work which I don’t want.

**Comment by Energieman** [comment]
OK OK, I had this issue with build failing on ios device in August 2024 on the lastest version as of the time, v1.5.2
Nothing seem to get the job done especially from this package issues.
Here is how I fixed it though

I added this post_install to my podfile and build started working fine on ios

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
    end
  end
end

If you are having problem merging that post_install to your podfile, well you can copy your existing pofile content to chatGPT and tell it to merge it for ya.
Here is my final podfile though

# Resolve react_native_pods.rb with node to allow for hoisting
# require Pod::Executable.execute_command('node', ['-p',
#   'require.resolve(
#     "react-native/scripts/react_native_pods.rb",
#     {paths: [process.argv[1]]},
#   )', __dir__]).strip

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
setup_permissions([
 'AppTrackingTransparency',
 # 'Bluetooth',
 # 'Calendars',
 # 'CalendarsWriteOnly',
 # 'Camera',
 # 'Contacts',
 # 'FaceID',
 # 'LocationAccuracy',
 # 'LocationAlways',
 # 'LocationWhenInUse',
 'MediaLibrary',
 # 'Microphone',
 # 'Motion',
 # 'Notifications',
 'PhotoLibrary',
 'PhotoLibraryAddOnly',
 # 'Reminders',
 # 'Siri',
 # 'SpeechRecognition',
 # 'StoreKit',
])

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'tremoved' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'tremovedTests' do
    inherit! :complete
    # Pods for testing
  end

  pod 'FirebaseCore', :modular_headers => true #when build consistently fail for the first time damilare
  pod 'GoogleUtilities', :modular_headers => true

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      end
    end
  end
end


I sure hope this helps someone, Because it helped me after 3 days.

**Comment by hungtooc** [comment]
> post_install do |installer| installer.pods_project.targets.each do |target| target.build_configurations.each do |config| config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64" end end end

@Energieman 
it really works! Thank you, I have been waiting for so long to fix this problem

**Comment by umutmisket** [comment]
I have tried @Energieman 's suggestion but i'm still facing the same error. I can not build for ios unless i install the rosetta which i don't want to do that. Any other suggestions ?

**Comment by Energieman** [comment]
> I have tried @Energieman 's suggestion but i'm still facing the same error. I can not build for ios unless i install the rosetta which i don't want to do that. Any other suggestions ?

Are you on the recent version of react-native? For example, I use 0.74.3
My last advice is to upgrade to the latest version of xcode (this may also require upgrading your OS), then upgrade your react-native to the latest version also.

**Comment by umutmisket** [comment]
I use react-native 0.75.3 and xCode Version 15.2 (15C500b)
There is an issue that I haven’t been able to fully resolve. I have two apps that are identical except for the bundle identifier and app names. One of them works perfectly, but the other does not.

**Comment by lebaphi** [comment]
@umutmisket you can try this one https://github.com/JoeyEamigh/react-native-text-recognition. It works for me.
